language: ruby
cache: bundler

notifications:
  email: false

services:
  - redis-server

matrix:
  include:
    - rvm: 2.4.3
      gemfile: Gemfile
    - rvm: 2.5.1
      gemfile: Gemfile
    - rvm: 2.6.0
      gemfile: gemfiles/railsmaster.gemfile
  allow_failures:
    - rvm: 2.6.0
      gemfile: gemfiles/railsmaster.gemfile
