name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_FORCE_RUBY_PLATFORM: 1
      CI: true
    services:
      redis:
        image: redis:5.0-alpine
        ports: ["6379:6379"]
        options: --health-cmd="redis-cli ping" --health-interval 1s --health-timeout 3s --health-retries 30
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7"]
        gemfile: ["gemfiles/rails5.gemfile", "gemfiles/rails6.gemfile", "gemfiles/railsmaster.gemfile"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle config --global gemfile ${{ matrix.gemfile }}
        bundle install
        bundle update
    - name: Run unit tests
      run: |
        bundle exec rake test
    - name: Run conformance tests for Rack
      run: |
        bundle exec rake anyt:rack
    - name: Run conformance tests for Rails
      run: |
        bundle exec rake anyt:rails
